### ISSUE TITLE
Could you made recovery tool for mp3 file?

### ISSUE THREAD

**Issue by HanalogInstruments** [david-pace/wave-recovery-tool#4]
Hi,

I have some encrypted mp3

```https://drive.google.com/drive/folders/1oKg7Zvl2E-9GvWVHtTwHyhxADAx1HEc0```

The encrypted data is 25805 bytes ( hex ) from the header

Could you made a repair for this case and error mp3 files?

**Comment by david-pace** [comment]
Could you please provide the following information:

- Which application was used to encrypt those files?
- How are those files usually decrypted?
- Are those files only encrypted or encrypted and corrupted at the same time?

**Comment by HanalogInstruments** [comment]
> Could you please provide the following information:
> 
> * Which application was used to encrypt those files?
> * How are those files usually decrypted?
> * Are those files only encrypted or encrypted and corrupted at the same time?

1. My files was encrypted by Stop/Djvu Ransomware
2. Yes, this ransomware encrypted all files but i know how to repair jpg,cr2,nef,... via hexedit but i don't know how to made batch process with python

**Comment by david-pace** [comment]
Have you figured out a way to restore your files with a Hex editor? Can you describe in detail what has to be done in the Hex editor? Do you copy the bytes starting from byte 25805 until the end into a new file? Is byte 25805 included or excluded? Does your hex editor start counting at 0 or 1 at the first byte? Are there any additional steps after that?

**Comment by HanalogInstruments** [comment]
Yes, I found that skip 4 bytes and write 12 zero bytes from the SOF and remove 334 bytes from EOF will work, i added the folder "New". The 25805 bytes is default
